[project]
name = "deploy-to-sagemaker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "metaflow>=2.17.0",
    "mlflow>=3.2.0",
    "numpy==1.26.4",
    "pyarrow==14.0.2",
    "seaborn>=0.13.2",
]
